# Generated by Django 6.1 on 2026-08-28 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('displacement_cc', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('aspiration', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehiclemake')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_from', models.PositiveIntegerField()),
                ('year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='vehicles.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('transmission_type', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], max_length=20)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_specifications', to='vehicles.engine')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='vehicles.vehiclegeneration')),
            ],
        ),
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_vehicles', to='vehicles.vehiclespecification')),
            ],
        ),
    ]
