# Generated by Django 6.1 on 2026-08-29 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uservehicle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uservehicle',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='uservehicle',
            name='odometer',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
