# Generated by Django 6.1 on 2026-09-03 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_uservehicle_user_alter_uservehicle_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('FLUID', 'Fluids & Lubrication'), ('FILTER', 'Filters'), ('BRAKE', 'Brakes'), ('TYRE', 'Tyres & Wheels'), ('ELECTRICAL', 'Electrical'), ('ENGINE', 'Engine'), ('TRANSMISSION', 'Transmission')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_visits', to='vehicles.uservehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REPLACED', 'Replaced'), ('CHANGED', 'Changed'), ('INSPECTED', 'Inspected'), ('SERVICED', 'Serviced')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('maintenance_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='maintenance.maintenanceitem')),
                ('service_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.servicevisit')),
            ],
        ),
    ]
